es = {
    "idtext": "<b>\nRyas Chk </> ID de Usuario [🌹]\n- - - - - - - - - - - - - - - - - - - - - - - - - - \nNombre de Usuario: @{username}\nID: <code>{user_id}</code>\nChat_ID: <code>{chat_id}</code>\n- - - - - - - - - - - - - - - - - - - - - - - - - - \n<code>Bot por: @Exzzex 🌸</code>\n</b>",
    "metext": "<b>\nRyas bot / Obtener información. [☁️]\n━━━━━━━━━\n[⌥] Información de usuario:\nNombre de usuario: @{username} \nID: <code>{user_id}</code>\n━━━━━━━━━\n[⌥] DB Informacion:\n[•] Plan: [<code>{rango}</code>] | [•] Spam: <code>{antispam}</code>\n[•] Expiracion Plan: <code>{expiration}</code>\n[•] Bans: [<code>{ban}</code>] | [•] Creditos: <code>{creditos}</code>\n</b>",
    "register_not": "<b> No estás registrado en la base de datos, usa /register</b>",
    "startx": "<b>\nBienvenido Ryas dev Bot  |  <code>{caracas_time}</code>\n                                                                                                 \n[{idioma_actual}] Hola @{username} Bienvenido a Ryas Telegram Bot, las puertas de enlace, las herramientas y las funciones se agregan constantemente, para saber que mis diferentes comandos usan los botones que se muestran aquí:\n━━━━━━━━━━━━━\n<code>Api Bot El estado es: Online ✅ | Ryas Api ¡Está en línea!!</code>\n</b>",
    "tools": "<b>\nHerramientas de RyasChk / Página 1\n━━━━━━━━━━━━\nGenerador de Bines:\nFormato: $gen 601120  \nCondición: ¡Desconectado! ❌\n━━━━━━━━━━━━\nSk Ckeck:\nFormato: $sk sk_live \nCondición: ¡Desconectado! ❌\n━━━━━━━━━━━━\nBuscador de BINs:\nFormato: $bin 601120  \nCondición: ¡Desconectado! ❌\n━━━━━━━━━━━━\nGenerador de Direcciones:\nFormato: $dir Código_de_País \nCondición: ¡Desconectado! ❌\n━━━━━━━━━━━━\nVerificación de Fraude de IP:\nFormato: $ip 1.1.1.1 \nCondición: ¡Desconectado! ❌\n━━━━━━━━━━━━\n</b>",
    "informacion_text": "<b>\nInformación de RyasChk ! 🌩\n━━━━━━━━━━━━\nÚltima Actualización: 04/04/25\nIdiomas Disponibles: Español, Inglés\nDesarrollador: @Exzzex\nFecha de Creación del Bot: 10/10/2024\n</b>",
    "description_text": "<b>\nDescripción de Ryas ! 🌩\n━━━━━━━━━━━━\nCanales:\nOnyx Updates: @próximamente\nCanal de Referencias de Onyx: @próximamente\nUsuarios Gratis de Onyx: @próximamente\n━━━━━━━━━━━━━━━━━\nInformación de Ryas:\n━━━━━━━\nDesarrollador: @Exzzex ✅ | [Comprar]\nDev Note: ¡Hola chicos, esta es la nueva versión de onyx, hecha con velocidad y buena experiencia de chequeo en mente!\n━━━━━━━\nVendedores:\n@coming soon | coming soon ✅ | [Buy]\n━━━━━━━━━━━━━━━━━\nOnyx Updates:\nVersión: 1.3.0 [✅]\nUpdate: próximamente p.m (GMT-5) [✅]\n━━━━━━━━━━━━━━━━━\nReporta problemas a: @Exzzex\n</b>",
    "close_text": "<b>\n¡Adiós! 🌩\n━━━━━━━━━━━━━━━━━\nDisfruta mi uso.\n</b>",
    "not_privilegios": "<b> No cuentas con los privilegios suficientes para usar este comando</b>",
    "msgformat": "<b>[<a href='t.me/ryascheckerbot'>⺢</a>] AdminHub: $msg id or all !texto</b>",
    "ryas_cloud": "<b>\n>_ $Comenzar_ Ryas Cloud | Bienvenido @{username} - Cloud DB \n\n[🇪🇸] Bienvenido a la nueva suscripción de Ryas Cloud, sus datos compartidos en la nube con Ryas se almacenarán aquí, navegue a través de los botones para descubrir qué es lo nuevo que tenemos para usted:      \n\n<code>Ryas Cloud Version:  0.0.1</code>  | Ryas Cloud Plan:  <code>Premium Cloud</code></b>",
    "registerx": "<b>あ » Interactúa con el bot sin ningún inconveniente, si deseas más información, usa los siguientes comandos.  \n\n↯ » Precios: /pricings\n↯ » Más información: /data</b>",
    "already_registered": "<b>あ » User {user} se encuentra registrado en la Base de Datos.</b>",
    "setpriv_usage": "Uso correcto: /setpriv <ID> <Privilegio>",
    "setpriv_value_error": "El ID y el privilegio deben ser números.",
    "setpriv_success": "Privilegio actualizado correctamente para el ID {user_id}.",
    "setpriv_not_found": "Ese ID no se encuentra en la base de datos.",
    "gen_response": "[⌥] Onyx Generator | Luhn Algo:\n━━━━━━━━━━━━━━\n{tarjetas}\n━━━━━━━━━━━━━━\n[ϟ] Bin : {bin_prefix}  |  [ϟ] Info:\n{banco} | {marca} | {tipo} | {pais} ({pais_codigo})\n━━━━━━━━━━━━━━\nbot by : @Astrozdev 🌤\n",
    "ban_message": "Astro Chk  Panel de Administrador [⚠️]\n- - - - - - - - - - - - - - -\n<b>Usuario Baneado</b>\nUsuario: @{username} [{target_user_id}]\nRazón: {ban_reason}\nAdministrador: @{admin_username} [{admin_id}]",
    "ban_usage": "Uso correcto: /ban <ID> <razón>",
    "ban_validation": "El ID de usuario debe ser un número entero.",
    "unban_message": "Ryas Chk  Panel de Administrador [⚠️]\n- - - - - - - - - - - - - - -\n<b>Usuario Desbaneado</b>\nUsuario: @{username} [{target_user_id}]\nFecha:  {fecha}\nAdministrador: @{admin_username} [{admin_id}]",
    "unban_usage": "Uso correcto: /unban <ID>",
    "unban_validation": "User ID must be an integer.",
    "block_message": "<b>Tu cuenta está baneada. No puedes acceder a esta información.</b>",
    "lang_message": "\nBienvenido @{username} - Cloud DB | LANG [{idioma_actual}] \n\nEstos son los datos sobre su idioma guardado en el DB, ¿desea cambiar?Seleccione un nuevo idioma en los botones a continuación:",
    "bin_not_found": "No se encontró información para el BIN {bin_number}.",
    "bin_usage": "Por favor, proporciona un número de BIN válido después del comando .bin",
    "bin_error": "Número de BIN inválido. Debe contener solo dígitos.",
    "bintext": "<b>({bandera}) - Datos para <code>{bin_number}</code> encontró -</b> \n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>#Bin<code>{bin_number}</code></b>\n<b>• Banco: <code>{bank_name}</code></b>\n<b>• Informacion: <code>{vendor} - {type} - {level}</code></b>\n<b>• Pais: <code>{pais} ({bandera})</code></b>\n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>Req By: @{username} [{rango}]</b>",
    "gatesx_message": "\n<b>Bienvenido a Astro / Astro gateways Online\n━━━━━━━━━━━━\nGates CMDS:  <code>0 Api Gates!</code> ✅ \n━━━━━━━━━━━━\nGates auth: <code>0</code>    |   Gates Charge: <code>0</code>\nGates CCN (Auth & Charge): <code>0</code>  |   Gates Mass Checking: <code>0</code>\n━━━━━━━━━━━━\n¡Selecciona el tipo de puerta que deseas para tu uso!</b>",
    "gen_message": "[<a href=\"t.me/Ryascheckerbot\">⌥</a>] <u>Ryas Generador</u> | <u>Luhn Algo:</u>\n━━━━━━━━━━━━━━\n-<code>{cc_first6}|{mes_display}|{ano_display}|{cvv_display}</code>-\n━━━━━━━━━━━━━━\n{cards_output}\n━━━━━━━━━━━━━━\n[<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Bin : {bin_first6}</code>  |  [<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Informacion:</code>\n{bin_text}\n━━━━━━━━━━━━━━\n<code>bot por : @astrozdev🌤</code>",
    "gen_loading": "<b><code>Generando tarjetas desde el contenedor... 🌤</b></code>",
    "gen_usage": "\n<b><u>Ryas Generador</u>[⛈]\nFormato: <code>$gen 60112088</code>\n<code>$gen 60112088 05/25 xxx</code>\n<code>$gen 60112088 05/xx</code></b>",
    "key_usage": "<b>[⽷] Usa /Key (Dias) Para generar la Key</b>",
    "key_system": "<b>\nAstro Chk | Systema De Key ☁️\n─────────────────────\nKey: <code>{Key}</code>\nExpiracion: <code>{date}</code>\n─────────────────────\nDias: <code>{dias}</code>\nPlan: <code>Premium</code>\nCanjeado por: @{username}\n</b>",
    "setrol_usage": "<b>Uso correcto: /setrol (ID) (Rol)\nEjemplo: /setrol 123456789 Admin</b>",
    "setrol_invalid": "<b>Rol inválido. Roles permitidos: Admin, Mod, Seller, Dev, Hunter</b>",
    "setrol_not_number": "<b>El ID debe ser un número.</b>",
    "setrol_not_found": "<b>Ese ID no está registrado en la base de datos.</b>",
    "setrol_already_has": "<b>⚠️ El usuario ya tiene el rol: {role}</b>",
    "setrol_success": "<b>✅ Rol actualizado correctamente:\nID: {id}\nNuevo Rol: {role}</b>",
    "setrol_no_permission": "<b>No tienes permisos para usar este comando.</b>",
    "mt_usage": "Uso correcto: /mt <número>. Ejemplo: /mt 100",
    "mt_invalid": "Por favor proporciona un número válido.",
    "mt_result": "La mitad de {numero} es {resultado}",
    "setlang_usage": "Uso correcto: .setlang <ID> <es|en>",
    "setlang_invalid_id": "El ID debe ser un número entero.",
    "setlang_invalid_lang": "Idioma no válido. Usa 'es' o 'en'.",
    "setlang_not_found": "Ese ID no está registrado en la base de datos.",
    "setlang_success": "✅ Idioma actualizado correctamente a '{idioma}' para el usuario con ID {id}.",
}


en = {
    "idtext": "<b>\nRyas Chk </> User ID [🌹]\n- - - - - - - - - - - - - - - - - - - - - - - - - - \nUsername: @{username}\nID: <code>{user_id}</code>\nChat_ID: <code>{chat_id}</code>\n- - - - - - - - - - - - - - - - - - - - - - - - - - \n<code>Bot by: @Exzzex 🌸</code>\n</b>",
    "metext": "<b>\nRyas bot / Get info. [☁️]\n━━━━━━━━━\n[⌥] User Info:\nUsername: @{username} \nID: <code>{user_id}</code>\n━━━━━━━━━\n[⌥] DB Info:\n[•] Plan: [<code>{rango}</code>] | [•] Spam: <code>{antispam}</code>\n[•] Expiration <code>{expiration}</code>\n[•] Bans: [<code>{ban}</code>] | [•] Credits: <code>{creditos}</code>\n</b>",
    "register_not": "<b> You are not registered in the database, use /register</b>",
    "startx": "<b>\nWelcome to Ryas dev Bot  |  <code>{caracas_time}</code>\n                                                                                                 \n[{idioma_actual}] Hello @{username} welcome to Ryas telegram bot, gateways, tools and functions are constantly being added, to know my different commands use the buttons shown here:\n━━━━━━━━━━━━━\n<code>Api Bot Status is: Online ✅ | Ryas Api is Online!!</code>\n</b>",
    "tools": "<b>\nRyasChk Tools / Page 1\n━━━━━━━━━━━━\nBin Generator:\nFormat: $gen 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nSk Ckeck:\nFormat: $sk sk_live \nCondition: Offline! ❌\n━━━━━━━━━━━━\nBIN Lookup:\nFormat: $bin 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nGen Address:\nFormat: $dir Country_code \nCondition: Offline! ❌\n━━━━━━━━━━━━\nIP Fraud Check:\nFormat: $ip 1.1.1.1 \nCondition: Offline! ❌\n━━━━━━━━━━━━\n</b>",
    "informacion_text": "<b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nBot Information:\nLast Update: 04/04/25\nAvailable Languages: English, Spanish\nDeveloper: @Exzzex\nBot Creation Date: 10/10/2024\n</b>",
    "description_text": "<b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nChannels:\nOnyx Updates: @coming soon\nOnyx References channel: @coming soon\nOnyx Free Users: @coming soon\n━━━━━━━━━━━━━━━━━\nRyas Information:\n━━━━━━━\nDev: @Exzzex ✅ | [Buy]\nDev Note: Hi guys, this is the new version of onyx, made with speed and good checking experience in mind!\n━━━━━━━\nSellers:\n@coming soon | coming soon ✅ | [Buy]\n━━━━━━━━━━━━━━━━━\nOnyx Updates:\nVersion: 1.3.0 [✅]\nUpdate: coming soon p.m (GMT-5) [✅]\n━━━━━━━━━━━━━━━━━\nReport problems to: @Exzzex\n</b>",
    "close_text": "<b>\nGood bye! 🌩\n━━━━━━━━━━━━━━━━━\nEnjoy my use.\n</b>",
    "not_privilegios": "<b> You do not have sufficient privileges to use this command</b>",
    "msgformat": "<b>[<a href='t.me/ryascheckerbot'>⺢</a>] AdminHub: $msg id or all !texto</b>",
    "ryas_cloud": "<b>\n>_ $Start_ Ryas Cloud | Welcome @{username} - Cloud DB\n\n[🇺🇸] Welcome to the new Ryas Cloud subscription, your details shared in the cloud with Ryas will be stored here, navigate through the buttons to discover what's new we have for you:      \n\n<code>Ryas Cloud Version:  0.0.1</code>  | Ryas Cloud Plan:  <code>Premium Cloud</code>\n</b>",
    "registerx": "<b>あ » Interact with the bot without any problems, if you want more information, use the following commands.\n\n↯ » Prices: /pricings\n↯ » More information: /data</b>",
    "already_registered": "<b>あ » User {user} is already registered in the Database.</b>",
    "setpriv_usage": "Correct usage: /setpriv <ID> <Privilege>",
    "setpriv_value_error": "ID and privilege must be numbers.",
    "setpriv_success": "Privilege updated correctly for ID {user_id}.",
    "setpriv_not_found": "That ID is not found in the database.",
    "gen_response": "[⌥] Onyx Generator | Luhn Algo:\n━━━━━━━━━━━━━━\n{tarjetas}\n━━━━━━━━━━━━━━\n[ϟ] Bin : {bin_prefix}  |  [ϟ] Info:\n{banco} | {marca} | {tipo} | {pais} ({pais_codigo})\n━━━━━━━━━━━━━━\nbot by : @Astrozdev 🌤\n",
    "ban_message": "Astro Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Banned</b>\nUser: @{username} [{target_user_id}]\nReason: {ban_reason}\nAdmin: @{admin_username} [{admin_id}]",
    "ban_usage": "Correct usage: /ban <ID> <reason>",
    "ban_validation": "User ID must be an integer.",
    "unban_message": "Ryas Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Unbanned</b>\nUser: @{username} [{target_user_id}]\nDate:  {fecha}\nAdmin: @{admin_username} [{admin_id}]",
    "unban_usage": "Correct usage: /unban <ID>",
    "unban_validation": "User ID must be an integer.",
    "block_message": "<b>Your account is banned. You cannot access this information.</b>",
    "lang_message": "\nWelcome @{username} - Cloud DB | LANG [{idioma_actual}] \n\nThese are the data about your language saved in the DB, do you want to change? Select a new language from the buttons below:",
    "bin_not_found": "No information found for BIN {bin_number}.",
    "bin_usage": "Please provide a valid BIN number after the .bin command",
    "bin_error": "Invalid BIN number. It must contain only digits.",
    "bintext": "<b>({bandera}) - Data For <code>{bin_number}</code> Found -</b> \n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>#Bin<code>{bin_number}</code></b>\n<b>• Bank: <code>{bank_name}</code></b>\n<b>• Info: <code>{vendor} - {type} - {level}</code></b>\n<b>• Country: <code>{pais} ({bandera})</code></b>\n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>Req By: @{username} [{rango}]</b>",
    "gatesx_message": "\n<b>Welcome to Onyx / Onyx gateways Online\n━━━━━━━━━━━━\nGates CMDS:  <code>0 Api Gates!</code> ✅ \n━━━━━━━━━━━━\nGates auth: <code>0</code>    |   Gates Charge: <code>0</code>\nGates CCN (Auth & Charge): <code>0</code>  |   Gates Mass Checking: <code>0</code>\n━━━━━━━━━━━━\nSelect the type of gate you want for your use!</b>",
    "gen_message": "[<a href=\"t.me/Ryascheckerbot\">⌥</a>] <u>Ryas Generator</u> | <u>Luhn Algo:</u>\n━━━━━━━━━━━━━━\n-<code>{cc_first6}|{mes_display}|{ano_display}|{cvv_display}</code>-\n━━━━━━━━━━━━━━\n{cards_output}\n━━━━━━━━━━━━━━\n[<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Bin : {bin_first6}</code>  |  [<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Info:</code>\n{bin_text}\n━━━━━━━━━━━━━━\n<code>bot by : @astrozdev🌤</code>",
    "gen_loading": "<b><code>Generating cards from the bin... 🌤</b></code>",
    "gen_usage": "\n<b><u>Ryas Generator</u>[⛈]\nFormat: <code>$gen 60112088</code>\n<code>$gen 60112088 05/25 xxx</code>\n<code>$gen 60112088 05/xx</code></b>",
    "key_usage": "<b>[⽷] Use /Key (Days) to generate the Key</b>",
    "key_system": "<b>\nAstro Chk | System Key ☁️\n─────────────────────\nKey: <code>{Key}</code>\nExpiration: <code>{date}</code>\n─────────────────────\nDays: <code>{dias}</code>\nPlan: <code>Premium</code>\nClaimed by: @{username}\n</b>",
    "setrol_usage": "<b>Correct usage: /setrol (ID) (Rol)\nExample: /setrol 123456789 Admin</b>",
    "setrol_invalid": "<b>Invalid role. Allowed roles: Admin, Mod, Seller, Dev, Hunter</b>",
    "setrol_not_number": "<b>The ID must be a number.</b>",
    "setrol_not_found": "<b>This ID is not registered in the database.</b>",
    "setrol_already_has": "<b>⚠️ The user already has the role: {role}</b>",
    "setrol_success": "<b>✅ Role successfully updated:\nID: {id}\nNew Role: {role}</b>",
    "setrol_no_permission": "<b>You do not have permission to use this command.</b>",
    "mt_usage": "Correct usage: /mt <number>. Example: /mt 100",
    "mt_invalid": "Please provide a valid number.",
    "mt_result": "The half of {numero} is {resultado}",
    "setlang_usage": "Correct usage: .setlang <ID> <es|en>",
    "setlang_invalid_id": "ID must be an integer.",
    "setlang_invalid_lang": "Invalid language. Use 'es' or 'en'.",
    "setlang_not_found": "That ID is not registered in the database.",
    "setlang_success": "✅ Language successfully updated to '{idioma}' for user with ID {id}.",
}


pt = {
    "idtext": "[PT] <b>\nRyas Chk </> User ID [🌹]\n- - - - - - - - - - - - - - - - - - - - - - - - - - \nUsername: @{username}\nID: <code>{user_id}</code>\nChat_ID: <code>{chat_id}</code>\n- - - - - - - - - - - - - - - - - - - - - - - - - - \n<code>Bot by: @Exzzex 🌸</code>\n</b>",
    "metext": "[PT] <b>\nRyas bot / Get info. [☁️]\n━━━━━━━━━\n[⌥] User Info:\nUsername: @{username} \nID: <code>{user_id}</code>\n━━━━━━━━━\n[⌥] DB Info:\n[•] Plan: [<code>{rango}</code>] | [•] Spam: <code>{antispam}</code>\n[•] Expiration <code>{expiration}</code>\n[•] Bans: [<code>{ban}</code>] | [•] Credits: <code>{creditos}</code>\n</b>",
    "register_not": "[PT] <b> You are not registered in the database, use /register</b>",
    "startx": "[PT] <b>\nWelcome to Ryas dev Bot  |  <code>{caracas_time}</code>\n                                                                                                 \n[{idioma_actual}] Hello @{username} welcome to Ryas telegram bot, gateways, tools and functions are constantly being added, to know my different commands use the buttons shown here:\n━━━━━━━━━━━━━\n<code>Api Bot Status is: Online ✅ | Ryas Api is Online!!</code>\n</b>",
    "tools": "[PT] <b>\nRyasChk Tools / Page 1\n━━━━━━━━━━━━\nBin Generator:\nFormat: $gen 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nSk Ckeck:\nFormat: $sk sk_live \nCondition: Offline! ❌\n━━━━━━━━━━━━\nBIN Lookup:\nFormat: $bin 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nGen Address:\nFormat: $dir Country_code \nCondition: Offline! ❌\n━━━━━━━━━━━━\nIP Fraud Check:\nFormat: $ip 1.1.1.1 \nCondition: Offline! ❌\n━━━━━━━━━━━━\n</b>",
    "informacion_text": "[PT] <b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nBot Information:\nLast Update: 04/04/25\nAvailable Languages: English, Spanish\nDeveloper: @Exzzex\nBot Creation Date: 10/10/2024\n</b>",
    "description_text": "[PT] <b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nChannels:\nOnyx Updates: @coming soon\nOnyx References channel: @coming soon\nOnyx Free Users: @coming soon\n━━━━━━━━━━━━━━━━━\nRyas Information:\n━━━━━━━\nDev: @Exzzex ✅ | [Buy]\nDev Note: Hi guys, this is the new version of onyx, made with speed and good checking experience in mind!\n━━━━━━━\nSellers:\n@coming soon | coming soon ✅ | [Buy]\n━━━━━━━━━━━━━━━━━\nOnyx Updates:\nVersion: 1.3.0 [✅]\nUpdate: coming soon p.m (GMT-5) [✅]\n━━━━━━━━━━━━━━━━━\nReport problems to: @Exzzex\n</b>",
    "close_text": "[PT] <b>\nGood bye! 🌩\n━━━━━━━━━━━━━━━━━\nEnjoy my use.\n</b>",
    "not_privilegios": "[PT] <b> You do not have sufficient privileges to use this command</b>",
    "msgformat": "[PT] <b>[<a href='t.me/ryascheckerbot'>⺢</a>] AdminHub: $msg id or all !texto</b>",
    "ryas_cloud": "[PT] <b>\n>_ $Start_ Ryas Cloud | Welcome @{username} - Cloud DB\n\n[🇺🇸] Welcome to the new Ryas Cloud subscription, your details shared in the cloud with Ryas will be stored here, navigate through the buttons to discover what's new we have for you:      \n\n<code>Ryas Cloud Version:  0.0.1</code>  | Ryas Cloud Plan:  <code>Premium Cloud</code>\n</b>",
    "registerx": "[PT] <b>あ » Interact with the bot without any problems, if you want more information, use the following commands.\n\n↯ » Prices: /pricings\n↯ » More information: /data</b>",
    "already_registered": "[PT] <b>あ » User {user} is already registered in the Database.</b>",
    "setpriv_usage": "[PT] Correct usage: /setpriv <ID> <Privilege>",
    "setpriv_value_error": "[PT] ID and privilege must be numbers.",
    "setpriv_success": "[PT] Privilege updated correctly for ID {user_id}.",
    "setpriv_not_found": "[PT] That ID is not found in the database.",
    "gen_response": "[PT] [⌥] Onyx Generator | Luhn Algo:\n━━━━━━━━━━━━━━\n{tarjetas}\n━━━━━━━━━━━━━━\n[ϟ] Bin : {bin_prefix}  |  [ϟ] Info:\n{banco} | {marca} | {tipo} | {pais} ({pais_codigo})\n━━━━━━━━━━━━━━\nbot by : @Astrozdev 🌤\n",
    "ban_message": "[PT] Astro Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Banned</b>\nUser: @{username} [{target_user_id}]\nReason: {ban_reason}\nAdmin: @{admin_username} [{admin_id}]",
    "ban_usage": "[PT] Correct usage: /ban <ID> <reason>",
    "ban_validation": "[PT] User ID must be an integer.",
    "unban_message": "[PT] Ryas Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Unbanned</b>\nUser: @{username} [{target_user_id}]\nDate:  {fecha}\nAdmin: @{admin_username} [{admin_id}]",
    "unban_usage": "[PT] Correct usage: /unban <ID>",
    "unban_validation": "[PT] User ID must be an integer.",
    "block_message": "[PT] <b>Your account is banned. You cannot access this information.</b>",
    "lang_message": "[PT] \nWelcome @{username} - Cloud DB | LANG [{idioma_actual}] \n\nThese are the data about your language saved in the DB, do you want to change? Select a new language from the buttons below:",
    "bin_not_found": "[PT] No information found for BIN {bin_number}.",
    "bin_usage": "[PT] Please provide a valid BIN number after the .bin command",
    "bin_error": "[PT] Invalid BIN number. It must contain only digits.",
    "bintext": "[PT] <b>({bandera}) - Data For <code>{bin_number}</code> Found -</b> \n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>#Bin<code>{bin_number}</code></b>\n<b>• Bank: <code>{bank_name}</code></b>\n<b>• Info: <code>{vendor} - {type} - {level}</code></b>\n<b>• Country: <code>{pais} ({bandera})</code></b>\n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>Req By: @{username} [{rango}]</b>",
    "gatesx_message": "[PT] \n<b>Welcome to Onyx / Onyx gateways Online\n━━━━━━━━━━━━\nGates CMDS:  <code>0 Api Gates!</code> ✅ \n━━━━━━━━━━━━\nGates auth: <code>0</code>    |   Gates Charge: <code>0</code>\nGates CCN (Auth & Charge): <code>0</code>  |   Gates Mass Checking: <code>0</code>\n━━━━━━━━━━━━\nSelect the type of gate you want for your use!</b>",
    "gen_message": "[PT] [<a href=\"t.me/Ryascheckerbot\">⌥</a>] <u>Ryas Generator</u> | <u>Luhn Algo:</u>\n━━━━━━━━━━━━━━\n-<code>{cc_first6}|{mes_display}|{ano_display}|{cvv_display}</code>-\n━━━━━━━━━━━━━━\n{cards_output}\n━━━━━━━━━━━━━━\n[<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Bin : {bin_first6}</code>  |  [<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Info:</code>\n{bin_text}\n━━━━━━━━━━━━━━\n<code>bot by : @astrozdev🌤</code>",
    "gen_loading": "[PT] <b><code>Generating cards from the bin... 🌤</b></code>",
    "gen_usage": "[PT] \n<b><u>Ryas Generator</u>[⛈]\nFormat: <code>$gen 60112088</code>\n<code>$gen 60112088 05/25 xxx</code>\n<code>$gen 60112088 05/xx</code></b>",
    "key_usage": "[PT] <b>[⽷] Use /Key (Days) to generate the Key</b>",
    "key_system": "[PT] <b>\nAstro Chk | System Key ☁️\n─────────────────────\nKey: <code>{Key}</code>\nExpiration: <code>{date}</code>\n─────────────────────\nDays: <code>{dias}</code>\nPlan: <code>Premium</code>\nClaimed by: @{username}\n</b>",
    "setrol_usage": "[PT] <b>Correct usage: /setrol (ID) (Rol)\nExample: /setrol 123456789 Admin</b>",
    "setrol_invalid": "[PT] <b>Invalid role. Allowed roles: Admin, Mod, Seller, Dev, Hunter</b>",
    "setrol_not_number": "[PT] <b>The ID must be a number.</b>",
    "setrol_not_found": "[PT] <b>This ID is not registered in the database.</b>",
    "setrol_already_has": "[PT] <b>⚠️ The user already has the role: {role}</b>",
    "setrol_success": "[PT] <b>✅ Role successfully updated:\nID: {id}\nNew Role: {role}</b>",
    "setrol_no_permission": "[PT] <b>You do not have permission to use this command.</b>",
    "mt_usage": "[PT] Correct usage: /mt <number>. Example: /mt 100",
    "mt_invalid": "[PT] Please provide a valid number.",
    "mt_result": "[PT] The half of {numero} is {resultado}",
    "setlang_usage": "[PT] Correct usage: .setlang <ID> <es|en>",
    "setlang_invalid_id": "[PT] ID must be an integer.",
    "setlang_invalid_lang": "[PT] Invalid language. Use 'es' or 'en'.",
    "setlang_not_found": "[PT] That ID is not registered in the database.",
    "setlang_success": "[PT] ✅ Language successfully updated to '{idioma}' for user with ID {id}.",
}


ru = {
    "idtext": "[RU] <b>\nRyas Chk </> User ID [🌹]\n- - - - - - - - - - - - - - - - - - - - - - - - - - \nUsername: @{username}\nID: <code>{user_id}</code>\nChat_ID: <code>{chat_id}</code>\n- - - - - - - - - - - - - - - - - - - - - - - - - - \n<code>Bot by: @Exzzex 🌸</code>\n</b>",
    "metext": "[RU] <b>\nRyas bot / Get info. [☁️]\n━━━━━━━━━\n[⌥] User Info:\nUsername: @{username} \nID: <code>{user_id}</code>\n━━━━━━━━━\n[⌥] DB Info:\n[•] Plan: [<code>{rango}</code>] | [•] Spam: <code>{antispam}</code>\n[•] Expiration <code>{expiration}</code>\n[•] Bans: [<code>{ban}</code>] | [•] Credits: <code>{creditos}</code>\n</b>",
    "register_not": "[RU] <b> You are not registered in the database, use /register</b>",
    "startx": "[RU] <b>\nWelcome to Ryas dev Bot  |  <code>{caracas_time}</code>\n                                                                                                 \n[{idioma_actual}] Hello @{username} welcome to Ryas telegram bot, gateways, tools and functions are constantly being added, to know my different commands use the buttons shown here:\n━━━━━━━━━━━━━\n<code>Api Bot Status is: Online ✅ | Ryas Api is Online!!</code>\n</b>",
    "tools": "[RU] <b>\nRyasChk Tools / Page 1\n━━━━━━━━━━━━\nBin Generator:\nFormat: $gen 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nSk Ckeck:\nFormat: $sk sk_live \nCondition: Offline! ❌\n━━━━━━━━━━━━\nBIN Lookup:\nFormat: $bin 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nGen Address:\nFormat: $dir Country_code \nCondition: Offline! ❌\n━━━━━━━━━━━━\nIP Fraud Check:\nFormat: $ip 1.1.1.1 \nCondition: Offline! ❌\n━━━━━━━━━━━━\n</b>",
    "informacion_text": "[RU] <b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nBot Information:\nLast Update: 04/04/25\nAvailable Languages: English, Spanish\nDeveloper: @Exzzex\nBot Creation Date: 10/10/2024\n</b>",
    "description_text": "[RU] <b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nChannels:\nOnyx Updates: @coming soon\nOnyx References channel: @coming soon\nOnyx Free Users: @coming soon\n━━━━━━━━━━━━━━━━━\nRyas Information:\n━━━━━━━\nDev: @Exzzex ✅ | [Buy]\nDev Note: Hi guys, this is the new version of onyx, made with speed and good checking experience in mind!\n━━━━━━━\nSellers:\n@coming soon | coming soon ✅ | [Buy]\n━━━━━━━━━━━━━━━━━\nOnyx Updates:\nVersion: 1.3.0 [✅]\nUpdate: coming soon p.m (GMT-5) [✅]\n━━━━━━━━━━━━━━━━━\nReport problems to: @Exzzex\n</b>",
    "close_text": "[RU] <b>\nGood bye! 🌩\n━━━━━━━━━━━━━━━━━\nEnjoy my use.\n</b>",
    "not_privilegios": "[RU] <b> You do not have sufficient privileges to use this command</b>",
    "msgformat": "[RU] <b>[<a href='t.me/ryascheckerbot'>⺢</a>] AdminHub: $msg id or all !texto</b>",
    "ryas_cloud": "[RU] <b>\n>_ $Start_ Ryas Cloud | Welcome @{username} - Cloud DB\n\n[🇺🇸] Welcome to the new Ryas Cloud subscription, your details shared in the cloud with Ryas will be stored here, navigate through the buttons to discover what's new we have for you:      \n\n<code>Ryas Cloud Version:  0.0.1</code>  | Ryas Cloud Plan:  <code>Premium Cloud</code>\n</b>",
    "registerx": "[RU] <b>あ » Interact with the bot without any problems, if you want more information, use the following commands.\n\n↯ » Prices: /pricings\n↯ » More information: /data</b>",
    "already_registered": "[RU] <b>あ » User {user} is already registered in the Database.</b>",
    "setpriv_usage": "[RU] Correct usage: /setpriv <ID> <Privilege>",
    "setpriv_value_error": "[RU] ID and privilege must be numbers.",
    "setpriv_success": "[RU] Privilege updated correctly for ID {user_id}.",
    "setpriv_not_found": "[RU] That ID is not found in the database.",
    "gen_response": "[RU] [⌥] Onyx Generator | Luhn Algo:\n━━━━━━━━━━━━━━\n{tarjetas}\n━━━━━━━━━━━━━━\n[ϟ] Bin : {bin_prefix}  |  [ϟ] Info:\n{banco} | {marca} | {tipo} | {pais} ({pais_codigo})\n━━━━━━━━━━━━━━\nbot by : @Astrozdev 🌤\n",
    "ban_message": "[RU] Astro Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Banned</b>\nUser: @{username} [{target_user_id}]\nReason: {ban_reason}\nAdmin: @{admin_username} [{admin_id}]",
    "ban_usage": "[RU] Correct usage: /ban <ID> <reason>",
    "ban_validation": "[RU] User ID must be an integer.",
    "unban_message": "[RU] Ryas Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Unbanned</b>\nUser: @{username} [{target_user_id}]\nDate:  {fecha}\nAdmin: @{admin_username} [{admin_id}]",
    "unban_usage": "[RU] Correct usage: /unban <ID>",
    "unban_validation": "[RU] User ID must be an integer.",
    "block_message": "[RU] <b>Your account is banned. You cannot access this information.</b>",
    "lang_message": "[RU] \nWelcome @{username} - Cloud DB | LANG [{idioma_actual}] \n\nThese are the data about your language saved in the DB, do you want to change? Select a new language from the buttons below:",
    "bin_not_found": "[RU] No information found for BIN {bin_number}.",
    "bin_usage": "[RU] Please provide a valid BIN number after the .bin command",
    "bin_error": "[RU] Invalid BIN number. It must contain only digits.",
    "bintext": "[RU] <b>({bandera}) - Data For <code>{bin_number}</code> Found -</b> \n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>#Bin<code>{bin_number}</code></b>\n<b>• Bank: <code>{bank_name}</code></b>\n<b>• Info: <code>{vendor} - {type} - {level}</code></b>\n<b>• Country: <code>{pais} ({bandera})</code></b>\n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>Req By: @{username} [{rango}]</b>",
    "gatesx_message": "[RU] \n<b>Welcome to Onyx / Onyx gateways Online\n━━━━━━━━━━━━\nGates CMDS:  <code>0 Api Gates!</code> ✅ \n━━━━━━━━━━━━\nGates auth: <code>0</code>    |   Gates Charge: <code>0</code>\nGates CCN (Auth & Charge): <code>0</code>  |   Gates Mass Checking: <code>0</code>\n━━━━━━━━━━━━\nSelect the type of gate you want for your use!</b>",
    "gen_message": "[RU] [<a href=\"t.me/Ryascheckerbot\">⌥</a>] <u>Ryas Generator</u> | <u>Luhn Algo:</u>\n━━━━━━━━━━━━━━\n-<code>{cc_first6}|{mes_display}|{ano_display}|{cvv_display}</code>-\n━━━━━━━━━━━━━━\n{cards_output}\n━━━━━━━━━━━━━━\n[<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Bin : {bin_first6}</code>  |  [<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Info:</code>\n{bin_text}\n━━━━━━━━━━━━━━\n<code>bot by : @astrozdev🌤</code>",
    "gen_loading": "[RU] <b><code>Generating cards from the bin... 🌤</b></code>",
    "gen_usage": "[RU] \n<b><u>Ryas Generator</u>[⛈]\nFormat: <code>$gen 60112088</code>\n<code>$gen 60112088 05/25 xxx</code>\n<code>$gen 60112088 05/xx</code></b>",
    "key_usage": "[RU] <b>[⽷] Use /Key (Days) to generate the Key</b>",
    "key_system": "[RU] <b>\nAstro Chk | System Key ☁️\n─────────────────────\nKey: <code>{Key}</code>\nExpiration: <code>{date}</code>\n─────────────────────\nDays: <code>{dias}</code>\nPlan: <code>Premium</code>\nClaimed by: @{username}\n</b>",
    "setrol_usage": "[RU] <b>Correct usage: /setrol (ID) (Rol)\nExample: /setrol 123456789 Admin</b>",
    "setrol_invalid": "[RU] <b>Invalid role. Allowed roles: Admin, Mod, Seller, Dev, Hunter</b>",
    "setrol_not_number": "[RU] <b>The ID must be a number.</b>",
    "setrol_not_found": "[RU] <b>This ID is not registered in the database.</b>",
    "setrol_already_has": "[RU] <b>⚠️ The user already has the role: {role}</b>",
    "setrol_success": "[RU] <b>✅ Role successfully updated:\nID: {id}\nNew Role: {role}</b>",
    "setrol_no_permission": "[RU] <b>You do not have permission to use this command.</b>",
    "mt_usage": "[RU] Correct usage: /mt <number>. Example: /mt 100",
    "mt_invalid": "[RU] Please provide a valid number.",
    "mt_result": "[RU] The half of {numero} is {resultado}",
    "setlang_usage": "[RU] Correct usage: .setlang <ID> <es|en>",
    "setlang_invalid_id": "[RU] ID must be an integer.",
    "setlang_invalid_lang": "[RU] Invalid language. Use 'es' or 'en'.",
    "setlang_not_found": "[RU] That ID is not registered in the database.",
    "setlang_success": "[RU] ✅ Language successfully updated to '{idioma}' for user with ID {id}.",
}


zh = {
    "idtext": "[ZH] <b>\nRyas Chk </> User ID [🌹]\n- - - - - - - - - - - - - - - - - - - - - - - - - - \nUsername: @{username}\nID: <code>{user_id}</code>\nChat_ID: <code>{chat_id}</code>\n- - - - - - - - - - - - - - - - - - - - - - - - - - \n<code>Bot by: @Exzzex 🌸</code>\n</b>",
    "metext": "[ZH] <b>\nRyas bot / Get info. [☁️]\n━━━━━━━━━\n[⌥] User Info:\nUsername: @{username} \nID: <code>{user_id}</code>\n━━━━━━━━━\n[⌥] DB Info:\n[•] Plan: [<code>{rango}</code>] | [•] Spam: <code>{antispam}</code>\n[•] Expiration <code>{expiration}</code>\n[•] Bans: [<code>{ban}</code>] | [•] Credits: <code>{creditos}</code>\n</b>",
    "register_not": "[ZH] <b> You are not registered in the database, use /register</b>",
    "startx": "[ZH] <b>\nWelcome to Ryas dev Bot  |  <code>{caracas_time}</code>\n                                                                                                 \n[{idioma_actual}] Hello @{username} welcome to Ryas telegram bot, gateways, tools and functions are constantly being added, to know my different commands use the buttons shown here:\n━━━━━━━━━━━━━\n<code>Api Bot Status is: Online ✅ | Ryas Api is Online!!</code>\n</b>",
    "tools": "[ZH] <b>\nRyasChk Tools / Page 1\n━━━━━━━━━━━━\nBin Generator:\nFormat: $gen 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nSk Ckeck:\nFormat: $sk sk_live \nCondition: Offline! ❌\n━━━━━━━━━━━━\nBIN Lookup:\nFormat: $bin 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nGen Address:\nFormat: $dir Country_code \nCondition: Offline! ❌\n━━━━━━━━━━━━\nIP Fraud Check:\nFormat: $ip 1.1.1.1 \nCondition: Offline! ❌\n━━━━━━━━━━━━\n</b>",
    "informacion_text": "[ZH] <b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nBot Information:\nLast Update: 04/04/25\nAvailable Languages: English, Spanish\nDeveloper: @Exzzex\nBot Creation Date: 10/10/2024\n</b>",
    "description_text": "[ZH] <b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nChannels:\nOnyx Updates: @coming soon\nOnyx References channel: @coming soon\nOnyx Free Users: @coming soon\n━━━━━━━━━━━━━━━━━\nRyas Information:\n━━━━━━━\nDev: @Exzzex ✅ | [Buy]\nDev Note: Hi guys, this is the new version of onyx, made with speed and good checking experience in mind!\n━━━━━━━\nSellers:\n@coming soon | coming soon ✅ | [Buy]\n━━━━━━━━━━━━━━━━━\nOnyx Updates:\nVersion: 1.3.0 [✅]\nUpdate: coming soon p.m (GMT-5) [✅]\n━━━━━━━━━━━━━━━━━\nReport problems to: @Exzzex\n</b>",
    "close_text": "[ZH] <b>\nGood bye! 🌩\n━━━━━━━━━━━━━━━━━\nEnjoy my use.\n</b>",
    "not_privilegios": "[ZH] <b> You do not have sufficient privileges to use this command</b>",
    "msgformat": "[ZH] <b>[<a href='t.me/ryascheckerbot'>⺢</a>] AdminHub: $msg id or all !texto</b>",
    "ryas_cloud": "[ZH] <b>\n>_ $Start_ Ryas Cloud | Welcome @{username} - Cloud DB\n\n[🇺🇸] Welcome to the new Ryas Cloud subscription, your details shared in the cloud with Ryas will be stored here, navigate through the buttons to discover what's new we have for you:      \n\n<code>Ryas Cloud Version:  0.0.1</code>  | Ryas Cloud Plan:  <code>Premium Cloud</code>\n</b>",
    "registerx": "[ZH] <b>あ » Interact with the bot without any problems, if you want more information, use the following commands.\n\n↯ » Prices: /pricings\n↯ » More information: /data</b>",
    "already_registered": "[ZH] <b>あ » User {user} is already registered in the Database.</b>",
    "setpriv_usage": "[ZH] Correct usage: /setpriv <ID> <Privilege>",
    "setpriv_value_error": "[ZH] ID and privilege must be numbers.",
    "setpriv_success": "[ZH] Privilege updated correctly for ID {user_id}.",
    "setpriv_not_found": "[ZH] That ID is not found in the database.",
    "gen_response": "[ZH] [⌥] Onyx Generator | Luhn Algo:\n━━━━━━━━━━━━━━\n{tarjetas}\n━━━━━━━━━━━━━━\n[ϟ] Bin : {bin_prefix}  |  [ϟ] Info:\n{banco} | {marca} | {tipo} | {pais} ({pais_codigo})\n━━━━━━━━━━━━━━\nbot by : @Astrozdev 🌤\n",
    "ban_message": "[ZH] Astro Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Banned</b>\nUser: @{username} [{target_user_id}]\nReason: {ban_reason}\nAdmin: @{admin_username} [{admin_id}]",
    "ban_usage": "[ZH] Correct usage: /ban <ID> <reason>",
    "ban_validation": "[ZH] User ID must be an integer.",
    "unban_message": "[ZH] Ryas Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Unbanned</b>\nUser: @{username} [{target_user_id}]\nDate:  {fecha}\nAdmin: @{admin_username} [{admin_id}]",
    "unban_usage": "[ZH] Correct usage: /unban <ID>",
    "unban_validation": "[ZH] User ID must be an integer.",
    "block_message": "[ZH] <b>Your account is banned. You cannot access this information.</b>",
    "lang_message": "[ZH] \nWelcome @{username} - Cloud DB | LANG [{idioma_actual}] \n\nThese are the data about your language saved in the DB, do you want to change? Select a new language from the buttons below:",
    "bin_not_found": "[ZH] No information found for BIN {bin_number}.",
    "bin_usage": "[ZH] Please provide a valid BIN number after the .bin command",
    "bin_error": "[ZH] Invalid BIN number. It must contain only digits.",
    "bintext": "[ZH] <b>({bandera}) - Data For <code>{bin_number}</code> Found -</b> \n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>#Bin<code>{bin_number}</code></b>\n<b>• Bank: <code>{bank_name}</code></b>\n<b>• Info: <code>{vendor} - {type} - {level}</code></b>\n<b>• Country: <code>{pais} ({bandera})</code></b>\n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>Req By: @{username} [{rango}]</b>",
    "gatesx_message": "[ZH] \n<b>Welcome to Onyx / Onyx gateways Online\n━━━━━━━━━━━━\nGates CMDS:  <code>0 Api Gates!</code> ✅ \n━━━━━━━━━━━━\nGates auth: <code>0</code>    |   Gates Charge: <code>0</code>\nGates CCN (Auth & Charge): <code>0</code>  |   Gates Mass Checking: <code>0</code>\n━━━━━━━━━━━━\nSelect the type of gate you want for your use!</b>",
    "gen_message": "[ZH] [<a href=\"t.me/Ryascheckerbot\">⌥</a>] <u>Ryas Generator</u> | <u>Luhn Algo:</u>\n━━━━━━━━━━━━━━\n-<code>{cc_first6}|{mes_display}|{ano_display}|{cvv_display}</code>-\n━━━━━━━━━━━━━━\n{cards_output}\n━━━━━━━━━━━━━━\n[<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Bin : {bin_first6}</code>  |  [<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Info:</code>\n{bin_text}\n━━━━━━━━━━━━━━\n<code>bot by : @astrozdev🌤</code>",
    "gen_loading": "[ZH] <b><code>Generating cards from the bin... 🌤</b></code>",
    "gen_usage": "[ZH] \n<b><u>Ryas Generator</u>[⛈]\nFormat: <code>$gen 60112088</code>\n<code>$gen 60112088 05/25 xxx</code>\n<code>$gen 60112088 05/xx</code></b>",
    "key_usage": "[ZH] <b>[⽷] Use /Key (Days) to generate the Key</b>",
    "key_system": "[ZH] <b>\nAstro Chk | System Key ☁️\n─────────────────────\nKey: <code>{Key}</code>\nExpiration: <code>{date}</code>\n─────────────────────\nDays: <code>{dias}</code>\nPlan: <code>Premium</code>\nClaimed by: @{username}\n</b>",
    "setrol_usage": "[ZH] <b>Correct usage: /setrol (ID) (Rol)\nExample: /setrol 123456789 Admin</b>",
    "setrol_invalid": "[ZH] <b>Invalid role. Allowed roles: Admin, Mod, Seller, Dev, Hunter</b>",
    "setrol_not_number": "[ZH] <b>The ID must be a number.</b>",
    "setrol_not_found": "[ZH] <b>This ID is not registered in the database.</b>",
    "setrol_already_has": "[ZH] <b>⚠️ The user already has the role: {role}</b>",
    "setrol_success": "[ZH] <b>✅ Role successfully updated:\nID: {id}\nNew Role: {role}</b>",
    "setrol_no_permission": "[ZH] <b>You do not have permission to use this command.</b>",
    "mt_usage": "[ZH] Correct usage: /mt <number>. Example: /mt 100",
    "mt_invalid": "[ZH] Please provide a valid number.",
    "mt_result": "[ZH] The half of {numero} is {resultado}",
    "setlang_usage": "[ZH] Correct usage: .setlang <ID> <es|en>",
    "setlang_invalid_id": "[ZH] ID must be an integer.",
    "setlang_invalid_lang": "[ZH] Invalid language. Use 'es' or 'en'.",
    "setlang_not_found": "[ZH] That ID is not registered in the database.",
    "setlang_success": "[ZH] ✅ Language successfully updated to '{idioma}' for user with ID {id}.",
}


ko = {
    "idtext": "[KO] <b>\nRyas Chk </> User ID [🌹]\n- - - - - - - - - - - - - - - - - - - - - - - - - - \nUsername: @{username}\nID: <code>{user_id}</code>\nChat_ID: <code>{chat_id}</code>\n- - - - - - - - - - - - - - - - - - - - - - - - - - \n<code>Bot by: @Exzzex 🌸</code>\n</b>",
    "metext": "[KO] <b>\nRyas bot / Get info. [☁️]\n━━━━━━━━━\n[⌥] User Info:\nUsername: @{username} \nID: <code>{user_id}</code>\n━━━━━━━━━\n[⌥] DB Info:\n[•] Plan: [<code>{rango}</code>] | [•] Spam: <code>{antispam}</code>\n[•] Expiration <code>{expiration}</code>\n[•] Bans: [<code>{ban}</code>] | [•] Credits: <code>{creditos}</code>\n</b>",
    "register_not": "[KO] <b> You are not registered in the database, use /register</b>",
    "startx": "[KO] <b>\nWelcome to Ryas dev Bot  |  <code>{caracas_time}</code>\n                                                                                                 \n[{idioma_actual}] Hello @{username} welcome to Ryas telegram bot, gateways, tools and functions are constantly being added, to know my different commands use the buttons shown here:\n━━━━━━━━━━━━━\n<code>Api Bot Status is: Online ✅ | Ryas Api is Online!!</code>\n</b>",
    "tools": "[KO] <b>\nRyasChk Tools / Page 1\n━━━━━━━━━━━━\nBin Generator:\nFormat: $gen 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nSk Ckeck:\nFormat: $sk sk_live \nCondition: Offline! ❌\n━━━━━━━━━━━━\nBIN Lookup:\nFormat: $bin 601120  \nCondition: Offline! ❌\n━━━━━━━━━━━━\nGen Address:\nFormat: $dir Country_code \nCondition: Offline! ❌\n━━━━━━━━━━━━\nIP Fraud Check:\nFormat: $ip 1.1.1.1 \nCondition: Offline! ❌\n━━━━━━━━━━━━\n</b>",
    "informacion_text": "[KO] <b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nBot Information:\nLast Update: 04/04/25\nAvailable Languages: English, Spanish\nDeveloper: @Exzzex\nBot Creation Date: 10/10/2024\n</b>",
    "description_text": "[KO] <b>\nRyas Description ! 🌩\n━━━━━━━━━━━━\nChannels:\nOnyx Updates: @coming soon\nOnyx References channel: @coming soon\nOnyx Free Users: @coming soon\n━━━━━━━━━━━━━━━━━\nRyas Information:\n━━━━━━━\nDev: @Exzzex ✅ | [Buy]\nDev Note: Hi guys, this is the new version of onyx, made with speed and good checking experience in mind!\n━━━━━━━\nSellers:\n@coming soon | coming soon ✅ | [Buy]\n━━━━━━━━━━━━━━━━━\nOnyx Updates:\nVersion: 1.3.0 [✅]\nUpdate: coming soon p.m (GMT-5) [✅]\n━━━━━━━━━━━━━━━━━\nReport problems to: @Exzzex\n</b>",
    "close_text": "[KO] <b>\nGood bye! 🌩\n━━━━━━━━━━━━━━━━━\nEnjoy my use.\n</b>",
    "not_privilegios": "[KO] <b> You do not have sufficient privileges to use this command</b>",
    "msgformat": "[KO] <b>[<a href='t.me/ryascheckerbot'>⺢</a>] AdminHub: $msg id or all !texto</b>",
    "ryas_cloud": "[KO] <b>\n>_ $Start_ Ryas Cloud | Welcome @{username} - Cloud DB\n\n[🇺🇸] Welcome to the new Ryas Cloud subscription, your details shared in the cloud with Ryas will be stored here, navigate through the buttons to discover what's new we have for you:      \n\n<code>Ryas Cloud Version:  0.0.1</code>  | Ryas Cloud Plan:  <code>Premium Cloud</code>\n</b>",
    "registerx": "[KO] <b>あ » Interact with the bot without any problems, if you want more information, use the following commands.\n\n↯ » Prices: /pricings\n↯ » More information: /data</b>",
    "already_registered": "[KO] <b>あ » User {user} is already registered in the Database.</b>",
    "setpriv_usage": "[KO] Correct usage: /setpriv <ID> <Privilege>",
    "setpriv_value_error": "[KO] ID and privilege must be numbers.",
    "setpriv_success": "[KO] Privilege updated correctly for ID {user_id}.",
    "setpriv_not_found": "[KO] That ID is not found in the database.",
    "gen_response": "[KO] [⌥] Onyx Generator | Luhn Algo:\n━━━━━━━━━━━━━━\n{tarjetas}\n━━━━━━━━━━━━━━\n[ϟ] Bin : {bin_prefix}  |  [ϟ] Info:\n{banco} | {marca} | {tipo} | {pais} ({pais_codigo})\n━━━━━━━━━━━━━━\nbot by : @Astrozdev 🌤\n",
    "ban_message": "[KO] Astro Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Banned</b>\nUser: @{username} [{target_user_id}]\nReason: {ban_reason}\nAdmin: @{admin_username} [{admin_id}]",
    "ban_usage": "[KO] Correct usage: /ban <ID> <reason>",
    "ban_validation": "[KO] User ID must be an integer.",
    "unban_message": "[KO] Ryas Chk  Admin Panel [⚠️]\n- - - - - - - - - - - - - - -\n<b>User Unbanned</b>\nUser: @{username} [{target_user_id}]\nDate:  {fecha}\nAdmin: @{admin_username} [{admin_id}]",
    "unban_usage": "[KO] Correct usage: /unban <ID>",
    "unban_validation": "[KO] User ID must be an integer.",
    "block_message": "[KO] <b>Your account is banned. You cannot access this information.</b>",
    "lang_message": "[KO] \nWelcome @{username} - Cloud DB | LANG [{idioma_actual}] \n\nThese are the data about your language saved in the DB, do you want to change? Select a new language from the buttons below:",
    "bin_not_found": "[KO] No information found for BIN {bin_number}.",
    "bin_usage": "[KO] Please provide a valid BIN number after the .bin command",
    "bin_error": "[KO] Invalid BIN number. It must contain only digits.",
    "bintext": "[KO] <b>({bandera}) - Data For <code>{bin_number}</code> Found -</b> \n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>#Bin<code>{bin_number}</code></b>\n<b>• Bank: <code>{bank_name}</code></b>\n<b>• Info: <code>{vendor} - {type} - {level}</code></b>\n<b>• Country: <code>{pais} ({bandera})</code></b>\n- - - - - - - - - - - - - - - - - - - - - - - - - \n<b>Req By: @{username} [{rango}]</b>",
    "gatesx_message": "[KO] \n<b>Welcome to Onyx / Onyx gateways Online\n━━━━━━━━━━━━\nGates CMDS:  <code>0 Api Gates!</code> ✅ \n━━━━━━━━━━━━\nGates auth: <code>0</code>    |   Gates Charge: <code>0</code>\nGates CCN (Auth & Charge): <code>0</code>  |   Gates Mass Checking: <code>0</code>\n━━━━━━━━━━━━\nSelect the type of gate you want for your use!</b>",
    "gen_message": "[KO] [<a href=\"t.me/Ryascheckerbot\">⌥</a>] <u>Ryas Generator</u> | <u>Luhn Algo:</u>\n━━━━━━━━━━━━━━\n-<code>{cc_first6}|{mes_display}|{ano_display}|{cvv_display}</code>-\n━━━━━━━━━━━━━━\n{cards_output}\n━━━━━━━━━━━━━━\n[<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Bin : {bin_first6}</code>  |  [<a href=\"t.me/Ryascheckerbot\">ϟ</a>] <code>Info:</code>\n{bin_text}\n━━━━━━━━━━━━━━\n<code>bot by : @astrozdev🌤</code>",
    "gen_loading": "[KO] <b><code>Generating cards from the bin... 🌤</b></code>",
    "gen_usage": "[KO] \n<b><u>Ryas Generator</u>[⛈]\nFormat: <code>$gen 60112088</code>\n<code>$gen 60112088 05/25 xxx</code>\n<code>$gen 60112088 05/xx</code></b>",
    "key_usage": "[KO] <b>[⽷] Use /Key (Days) to generate the Key</b>",
    "key_system": "[KO] <b>\nAstro Chk | System Key ☁️\n─────────────────────\nKey: <code>{Key}</code>\nExpiration: <code>{date}</code>\n─────────────────────\nDays: <code>{dias}</code>\nPlan: <code>Premium</code>\nClaimed by: @{username}\n</b>",
    "setrol_usage": "[KO] <b>Correct usage: /setrol (ID) (Rol)\nExample: /setrol 123456789 Admin</b>",
    "setrol_invalid": "[KO] <b>Invalid role. Allowed roles: Admin, Mod, Seller, Dev, Hunter</b>",
    "setrol_not_number": "[KO] <b>The ID must be a number.</b>",
    "setrol_not_found": "[KO] <b>This ID is not registered in the database.</b>",
    "setrol_already_has": "[KO] <b>⚠️ The user already has the role: {role}</b>",
    "setrol_success": "[KO] <b>✅ Role successfully updated:\nID: {id}\nNew Role: {role}</b>",
    "setrol_no_permission": "[KO] <b>You do not have permission to use this command.</b>",
    "mt_usage": "[KO] Correct usage: /mt <number>. Example: /mt 100",
    "mt_invalid": "[KO] Please provide a valid number.",
    "mt_result": "[KO] The half of {numero} is {resultado}",
    "setlang_usage": "[KO] Correct usage: .setlang <ID> <es|en>",
    "setlang_invalid_id": "[KO] ID must be an integer.",
    "setlang_invalid_lang": "[KO] Invalid language. Use 'es' or 'en'.",
    "setlang_not_found": "[KO] That ID is not registered in the database.",
    "setlang_success": "[KO] ✅ Language successfully updated to '{idioma}' for user with ID {id}.",
}


